  IF EXISTS(SELECT 1 FROM information_schema.tables 
  WHERE table_name = '
'__EFMigrationsHistory'' AND table_schema = DATABASE()) 
BEGIN
CREATE TABLE `__EFMigrationsHistory` (
    `MigrationId` varchar(150) NOT NULL,
    `ProductVersion` varchar(32) NOT NULL,
    PRIMARY KEY (`MigrationId`)
);

END;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20201022193150_Initial', '3.1.9');

ALTER TABLE `TORDENTRABAJO` ADD `ClaveDiseno` varchar(767) NULL;

CREATE TABLE `vc_diseno` (
    `ClaveDiseno` varchar(767) NOT NULL,
    `TamañoFotocelda_Alto_Std` double NULL,
    `TamañoFotocelda_Alto_Min` double NULL,
    `TamañoFotocelda_Alto_Max` double NULL,
    `TamañoFotocelda_Alto_Unidad` text NULL,
    `TamañoFotocelda_Ancho_Std` double NULL,
    `TamañoFotocelda_Ancho_Min` double NULL,
    `TamañoFotocelda_Ancho_Max` double NULL,
    `TamañoFotocelda_Ancho_Unidad` text NULL,
    `TamañoDiseño_Alto_Std` double NULL,
    `TamañoDiseño_Alto_Min` double NULL,
    `TamañoDiseño_Alto_Max` double NULL,
    `TamañoDiseño_Alto_Unidad` text NULL,
    `TamañoDiseño_Ancho_Std` double NULL,
    `TamañoDiseño_Ancho_Min` double NULL,
    `TamañoDiseño_Ancho_Max` double NULL,
    `TamañoDiseño_Ancho_Unidad` text NULL,
    `CodigoBarras` text NULL,
    `SobreViajero` text NULL,
    `ClaveIntelisis` text NULL,
    `FiguraFinal` int NOT NULL,
    PRIMARY KEY (`ClaveDiseno`)
);

CREATE TABLE `vc_procesos` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `Comentarios` text NULL,
    `TamañoDiseño_Alto_Std` double NULL,
    `TamañoDiseño_Alto_Min` double NULL,
    `TamañoDiseño_Alto_Max` double NULL,
    `TamañoDiseño_Alto_Unidad` text NULL,
    `TamañoDiseño_Ancho_Std` double NULL,
    `TamañoDiseño_Ancho_Min` double NULL,
    `TamañoDiseño_Ancho_Max` double NULL,
    `TamañoDiseño_Ancho_Unidad` text NULL,
    `FiguraEmbobinado` int NOT NULL,
    `ProcesoId` int NOT NULL,
    `ClaveDiseno` varchar(767) NOT NULL,
    `Discriminator` text NOT NULL,
    `ProveedorTinta` text NULL,
    `TipoTinta` text NULL,
    `ReferenciaEntonacion` text NULL,
    `TipoImpresion` text NULL,
    `Dureza_Std` double NULL,
    `Dureza_Min` double NULL,
    `Dureza_Max` double NULL,
    `Dureza_Unidad` text NULL,
    `ClaveResina` text NULL,
    `ClaveCatalizador` text NULL,
    `AplicacionAdhesivo_Std` double NULL,
    `AplicacionAdhesivo_Min` double NULL,
    `AplicacionAdhesivo_Max` double NULL,
    `AplicacionAdhesivo_Unidad` text NULL,
    `RelacionAdhesivo_Std` double NULL,
    `RelacionAdhesivo_Min` double NULL,
    `RelacionAdhesivo_Max` double NULL,
    `RelacionAdhesivo_Unidad` text NULL,
    `Curling_Std` double NULL,
    `Curling_Min` double NULL,
    `Curling_Max` double NULL,
    `Curling_Unidad` text NULL,
    `FuerzaLaminacionUno_Std` double NULL,
    `FuerzaLaminacionUno_Min` double NULL,
    `FuerzaLaminacionUno_Max` double NULL,
    `FuerzaLaminacionUno_Unidad` text NULL,
    `FuerzaLaminacionDos_Std` double NULL,
    `FuerzaLaminacionDos_Min` double NULL,
    `FuerzaLaminacionDos_Max` double NULL,
    `FuerzaLaminacionDos_Unidad` text NULL,
    `MedidaCore` int NULL,
    `MarcaCore` text NULL,
    `ControlPrincipal` text NULL,
    `ControlPrincipalTolerancia_Std` double NULL,
    `ControlPrincipalTolerancia_Min` double NULL,
    `ControlPrincipalTolerancia_Max` double NULL,
    `ControlPrincipalTolerancia_Unidad` text NULL,
    `ControlSecundario` text NULL,
    `PistaDoble` bit NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_vc_procesos_vc_diseno_ClaveDiseno` FOREIGN KEY (`ClaveDiseno`) REFERENCES `vc_diseno` (`ClaveDiseno`) ON DELETE CASCADE,
    CONSTRAINT `FK_vc_procesos_Procesos_ProcesoId` FOREIGN KEY (`ProcesoId`) REFERENCES `Procesos` (`ID`) ON DELETE CASCADE
);

CREATE TABLE `vc_parametros` (
    `Id` int NOT NULL AUTO_INCREMENT,
    `MaquinaId` int NOT NULL,
    `FechaCaptura` datetime NOT NULL,
    `FechaActualizacion` datetime NOT NULL,
    `Velocidad_Std` double NULL,
    `Velocidad_Min` double NULL,
    `Velocidad_Max` double NULL,
    `Velocidad_Unidad` text NULL,
    `TaperTension_Std` double NULL,
    `TaperTension_Min` double NULL,
    `TaperTension_Max` double NULL,
    `TaperTension_Unidad` text NULL,
    `BaseProcesoId` int NOT NULL,
    `Discriminator` text NOT NULL,
    `IsGearless` bit NULL,
    `PresionRodilloPisorCalandra_Std` double NULL,
    `PresionRodilloPisorCalandra_Min` double NULL,
    `PresionRodilloPisorCalandra_Max` double NULL,
    `PresionRodilloPisorCalandra_Unidad` text NULL,
    `PresionRodilloPisorTambor_Std` double NULL,
    `PresionRodilloPisorTambor_Min` double NULL,
    `PresionRodilloPisorTambor_Max` double NULL,
    `PresionRodilloPisorTambor_Unidad` text NULL,
    `PresionRodilloPisorEmbobinador_Std` double NULL,
    `PresionRodilloPisorEmbobinador_Min` double NULL,
    `PresionRodilloPisorEmbobinador_Max` double NULL,
    `PresionRodilloPisorEmbobinador_Unidad` text NULL,
    `PotenciaTratador_Std` double NULL,
    `PotenciaTratador_Min` double NULL,
    `PotenciaTratador_Max` double NULL,
    `PotenciaTratador_Unidad` text NULL,
    `TensionBanda_Puente_Std` double NULL,
    `TensionBanda_Puente_Min` double NULL,
    `TensionBanda_Puente_Max` double NULL,
    `TensionBanda_Puente_Unidad` text NULL,
    `TemperaturaPuente_Std` text NULL,
    `TemperaturaPuente_Min` text NULL,
    `TemperaturaPuente_Max` text NULL,
    `TemperaturaPuente_Unidad` text NULL,
    `TemperaturaIntergrupos_Std` text NULL,
    `TemperaturaIntergrupos_Min` text NULL,
    `TemperaturaIntergrupos_Max` text NULL,
    `TemperaturaIntergrupos_Unidad` text NULL,
    `TensionArrastre_Desbobinador_Std` double NULL,
    `TensionArrastre_Desbobinador_Min` double NULL,
    `TensionArrastre_Desbobinador_Max` double NULL,
    `TensionArrastre_Desbobinador_Unidad` text NULL,
    `TensionRodilloRefrigeranteG_Std` double NULL,
    `TensionRodilloRefrigeranteG_Min` double NULL,
    `TensionRodilloRefrigeranteG_Max` double NULL,
    `TensionRodilloRefrigeranteG_Unidad` text NULL,
    `FuerzaAprieteG_Std` double NULL,
    `FuerzaAprieteG_Min` double NULL,
    `FuerzaAprieteG_Max` double NULL,
    `FuerzaAprieteG_Unidad` text NULL,
    `IndiceReduccionG_Std` double NULL,
    `IndiceReduccionG_Min` double NULL,
    `IndiceReduccionG_Max` double NULL,
    `IndiceReduccionG_Unidad` text NULL,
    `DiametroInicialG` int NULL,
    `DiametroFinalG` int NULL,
    `PresionBalancinEmbobinadorE_Std` double NULL,
    `PresionBalancinEmbobinadorE_Min` double NULL,
    `PresionBalancinEmbobinadorE_Max` double NULL,
    `PresionBalancinEmbobinadorE_Unidad` text NULL,
    `PresionBalancinDesbobinadorE_Std` double NULL,
    `PresionBalancinDesbobinadorE_Min` double NULL,
    `PresionBalancinDesbobinadorE_Max` double NULL,
    `PresionBalancinDesbobinadorE_Unidad` text NULL,
    `OffsetE_Std` text NULL,
    `OffsetE_Min` text NULL,
    `OffsetE_Max` text NULL,
    `OffsetE_Unidad` text NULL,
    `TemperaturaResina_Std` double NULL,
    `TemperaturaResina_Min` double NULL,
    `TemperaturaResina_Max` double NULL,
    `TemperaturaResina_Unidad` text NULL,
    `TemperaturaCatalizador_Std` double NULL,
    `TemperaturaCatalizador_Min` double NULL,
    `TemperaturaCatalizador_Max` double NULL,
    `TemperaturaCatalizador_Unidad` text NULL,
    `TemperaturaRodilloAplicador_Std` double NULL,
    `TemperaturaRodilloAplicador_Min` double NULL,
    `TemperaturaRodilloAplicador_Max` double NULL,
    `TemperaturaRodilloAplicador_Unidad` text NULL,
    `TemperaturaRodilloLaminador_Std` double NULL,
    `TemperaturaRodilloLaminador_Min` double NULL,
    `TemperaturaRodilloLaminador_Max` double NULL,
    `TemperaturaRodilloLaminador_Unidad` text NULL,
    `PresionRodilloMangas_Std` double NULL,
    `PresionRodilloMangas_Min` double NULL,
    `PresionRodilloMangas_Max` double NULL,
    `PresionRodilloMangas_Unidad` text NULL,
    `RodilloLaminadorPresionIzquierda_Std` double NULL,
    `RodilloLaminadorPresionIzquierda_Min` double NULL,
    `RodilloLaminadorPresionIzquierda_Max` double NULL,
    `RodilloLaminadorPresionIzquierda_Unidad` text NULL,
    `RodilloPresorPresionIzquierda_Std` double NULL,
    `RodilloPresorPresionIzquierda_Min` double NULL,
    `RodilloPresorPresionIzquierda_Max` double NULL,
    `RodilloPresorPresionIzquierda_Unidad` text NULL,
    `GalgaRodilloAplicacionIzquierda_Std` double NULL,
    `GalgaRodilloAplicacionIzquierda_Min` double NULL,
    `GalgaRodilloAplicacionIzquierda_Max` double NULL,
    `GalgaRodilloAplicacionIzquierda_Unidad` text NULL,
    `TensionDesbobinadorUno_Std` double NULL,
    `TensionDesbobinadorUno_Min` double NULL,
    `TensionDesbobinadorUno_Max` double NULL,
    `TensionDesbobinadorUno_Unidad` text NULL,
    `TensionDesbobinadorDos_Std` double NULL,
    `TensionDesbobinadorDos_Min` double NULL,
    `TensionDesbobinadorDos_Max` double NULL,
    `TensionDesbobinadorDos_Unidad` text NULL,
    `TensionBobinador_Std` double NULL,
    `TensionBobinador_Min` double NULL,
    `TensionBobinador_Max` double NULL,
    `TensionBobinador_Unidad` text NULL,
    `TensionPuente_Std` double NULL,
    `TensionPuente_Min` double NULL,
    `TensionPuente_Max` double NULL,
    `TensionPuente_Unidad` text NULL,
    `PresionRodilloAplicador_Std` double NULL,
    `PresionRodilloAplicador_Min` double NULL,
    `PresionRodilloAplicador_Max` double NULL,
    `PresionRodilloAplicador_Unidad` text NULL,
    `RodilloLaminadorPresionDerecha_Std` double NULL,
    `RodilloLaminadorPresionDerecha_Min` double NULL,
    `RodilloLaminadorPresionDerecha_Max` double NULL,
    `RodilloLaminadorPresionDerecha_Unidad` text NULL,
    `RodilloPresorPresionDerecha_Std` double NULL,
    `RodilloPresorPresionDerecha_Min` double NULL,
    `RodilloPresorPresionDerecha_Max` double NULL,
    `RodilloPresorPresionDerecha_Unidad` text NULL,
    `GalgaRodilloAplicacionDerecha_Std` double NULL,
    `GalgaRodilloAplicacionDerecha_Min` double NULL,
    `GalgaRodilloAplicacionDerecha_Max` double NULL,
    `GalgaRodilloAplicacionDerecha_Unidad` text NULL,
    `TensionDesbobinador_Std` double NULL,
    `TensionDesbobinador_Min` double NULL,
    `TensionDesbobinador_Max` double NULL,
    `TensionDesbobinador_Unidad` text NULL,
    `TensionEnbobinadorSuperior_Std` double NULL,
    `TensionEnbobinadorSuperior_Min` double NULL,
    `TensionEnbobinadorSuperior_Max` double NULL,
    `TensionEnbobinadorSuperior_Unidad` text NULL,
    `TensionEnbobinadorInferior_Std` double NULL,
    `TensionEnbobinadorInferior_Min` double NULL,
    `TensionEnbobinadorInferior_Max` double NULL,
    `TensionEnbobinadorInferior_Unidad` text NULL,
    `PresionRodilloSuperior_Std` double NULL,
    `PresionRodilloSuperior_Min` double NULL,
    `PresionRodilloSuperior_Max` double NULL,
    `PresionRodilloSuperior_Unidad` text NULL,
    `PresionRodilloInferior_Std` double NULL,
    `PresionRodilloInferior_Min` double NULL,
    `PresionRodilloInferior_Max` double NULL,
    `PresionRodilloInferior_Unidad` text NULL,
    PRIMARY KEY (`Id`),
    CONSTRAINT `FK_vc_parametros_vc_procesos_BaseProcesoId` FOREIGN KEY (`BaseProcesoId`) REFERENCES `vc_procesos` (`Id`) ON DELETE CASCADE,
    CONSTRAINT `FK_vc_parametros_Maquinas_MaquinaId` FOREIGN KEY (`MaquinaId`) REFERENCES `Maquinas` (`Id`) ON DELETE CASCADE
);

CREATE INDEX `IX_TORDENTRABAJO_ClaveDiseno` ON `TORDENTRABAJO` (`ClaveDiseno`);

CREATE INDEX `IX_vc_parametros_MaquinaId` ON `vc_parametros` (`MaquinaId`);

CREATE UNIQUE INDEX `IndexParametrosProcesoMaquina` ON `vc_parametros` (`BaseProcesoId`, `MaquinaId`);

CREATE INDEX `IX_vc_procesos_ClaveDiseno` ON `vc_procesos` (`ClaveDiseno`);

CREATE UNIQUE INDEX `IndexProcesoDiseno` ON `vc_procesos` (`ProcesoId`, `ClaveDiseno`);

ALTER TABLE `TORDENTRABAJO` ADD CONSTRAINT `FK_TORDENTRABAJO_vc_diseno_ClaveDiseno` FOREIGN KEY (`ClaveDiseno`) REFERENCES `vc_diseno` (`ClaveDiseno`) ON DELETE RESTRICT;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20201202230526_VC', '3.1.9');

ALTER TABLE Maquinas MODIFY `NombreMaquina` text NOT NULL;

ALTER TABLE Maquinas MODIFY `ModeloMaquina` text NOT NULL;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20201218160836_updateModeloMaquina', '3.1.9');

