//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibModeloDB.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProduccionModeloContainer : DbContext
    {
        public ProduccionModeloContainer()
            : base("name=ProduccionModeloContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<FamiliaMateriales> FamiliasMateriales { get; set; }
        public virtual DbSet<Material> Materiales { get; set; }
        public virtual DbSet<Impresora> Impresoras { get; set; }
        public virtual DbSet<Rodillo> Rodillos { get; set; }
        public virtual DbSet<TipoProducto> TiposProducto { get; set; }
        public virtual DbSet<Receta> Recetas { get; set; }
    }
}
