//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelNoblezaControlProduccion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ActivarEnvio {
            get {
                return ((bool)(this["ActivarEnvio"]));
            }
            set {
                this["ActivarEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BasculaActivarEnvio {
            get {
                return ((bool)(this["BasculaActivarEnvio"]));
            }
            set {
                this["BasculaActivarEnvio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int BasculaBaudRate {
            get {
                return ((int)(this["BasculaBaudRate"]));
            }
            set {
                this["BasculaBaudRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public string BasculaCaracterFinLinea {
            get {
                return ((string)(this["BasculaCaracterFinLinea"]));
            }
            set {
                this["BasculaCaracterFinLinea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BasculaconectarAlIniciar {
            get {
                return ((bool)(this["BasculaconectarAlIniciar"]));
            }
            set {
                this["BasculaconectarAlIniciar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int BasculaFin {
            get {
                return ((int)(this["BasculaFin"]));
            }
            set {
                this["BasculaFin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int BasculaInicio {
            get {
                return ((int)(this["BasculaInicio"]));
            }
            set {
                this["BasculaInicio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int BasculaIntervalo {
            get {
                return ((int)(this["BasculaIntervalo"]));
            }
            set {
                this["BasculaIntervalo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM3")]
        public global::libBascula.Puertos BasculaPuerto {
            get {
                return ((global::libBascula.Puertos)(this["BasculaPuerto"]));
            }
            set {
                this["BasculaPuerto"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int BasculaReadTimeOut {
            get {
                return ((int)(this["BasculaReadTimeOut"]));
            }
            set {
                this["BasculaReadTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BasculaShowUnidad {
            get {
                return ((bool)(this["BasculaShowUnidad"]));
            }
            set {
                this["BasculaShowUnidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BasculaTextoAEnviar {
            get {
                return ((string)(this["BasculaTextoAEnviar"]));
            }
            set {
                this["BasculaTextoAEnviar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("kg")]
        public global::libBascula.Unidad BasculaUnidad {
            get {
                return ((global::libBascula.Unidad)(this["BasculaUnidad"]));
            }
            set {
                this["BasculaUnidad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Theme_Silver_Active {
            get {
                return ((bool)(this["Theme_Silver_Active"]));
            }
            set {
                this["Theme_Silver_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Theme_Dark_Active {
            get {
                return ((bool)(this["Theme_Dark_Active"]));
            }
            set {
                this["Theme_Dark_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Theme_Blue_Active {
            get {
                return ((bool)(this["Theme_Blue_Active"]));
            }
            set {
                this["Theme_Blue_Active"] = value;
            }
        }
    }
}
